# Generated by Django 2.2.5 on 2020-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_search', models.CharField(max_length=1000)),
                ('youtube_result', models.CharField(max_length=1000)),
            ],
        ),
    ]
