# Generated by Django 3.0.6 on 2020-05-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='youtube_result',
        ),
        migrations.AddField(
            model_name='history',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_search',
            field=models.CharField(max_length=255),
        ),
    ]
