# Generated by Django 2.2.5 on 2020-05-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20200510_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='youtube_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
